### ISSUE TITLE
Doesn't support JSX

### ISSUE THREAD

**Issue by naxsooley** [nolanlawson/rollupify#42] opened 2016-10-06 08:55 UTC
According to docs I've a correct setup of transforms [rollupify, babelify].

In my `.babelrc` I've:

```
{
  "presets": [
    "stage-1",
    ["es2015", {"loose": true}],
    "react"
  ]
}
```

When I try to use rollupify with react, I get a message like:

```
Error: Unexpected token (39:6) in /home/file.js while parsing file: /home/app.js
```

Errors are thrown for JSX (`return <jsx>`) appearances like:

```
return (
      <DropdownButton />
)
```

Is there some kind of workaround for this?

**Comment by nolanlawson** [comment] 2016-10-25 01:04
Duplicate of #1, and no sorry there is no workaround.

**Closed as completed by nolanlawson** 2016-10-25 01:04 UTC
